### ISSUE TITLE
Invalid message length from Atmosphere

### ISSUE THREAD

**Issue by davidsowerby** [davidsowerby/krail#339]
currently only appears when run in the IDE, see #338 

Mar 02, 2015 3:45:24 PM com.vaadin.server.DefaultErrorHandler doDefault
SEVERE: 
java.io.IOException: Invalid message length undefined
	at com.vaadin.server.communication.AtmospherePushConnection$FragmentedMessage.<init>(AtmospherePushConnection.java:77)
	at com.vaadin.server.communication.AtmospherePushConnection.receiveMessage(AtmospherePushConnection.java:208)
	at com.vaadin.server.communication.PushHandler$3.run(PushHandler.java:163)
	at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:253)
	at com.vaadin.server.communication.PushHandler.access$200(PushHandler.java:56)
	at com.vaadin.server.communication.PushHandler$1.onRequest(PushHandler.java:76)
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:187)
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:98)
	at org.atmosphere.container.TomcatWebSocketUtil.doService(TomcatWebSocketUtil.java:154)
	at org.atmosphere.container.Tomcat7Servlet30SupportWithWebSocket.service(Tomcat7Servlet30SupportWithWebSocket.java:62)
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:1809)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:434)
	at org.atmosphere.websocket.DefaultWebSocketProcessor$2.run(DefaultWebSocketProcessor.java:287)
	at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:281)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:305)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatchReader(DefaultWebSocketProcessor.java:645)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:406)
	at org.atmosphere.container.TomcatWebSocketHandler.onTextData(TomcatWebSocketHandler.java:100)
	at org.apache.catalina.websocket.StreamInbound.doOnTextData(StreamInbound.java:191)
	at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:139)
	at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:88)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: For input string: "undefined"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.vaadin.server.communication.AtmospherePushConnection$FragmentedMessage.<init>(AtmospherePushConnection.java:75)
	... 27 more

Mar 02, 2015 3:45:25 PM com.vaadin.server.DefaultErrorHandler doDefault
SEVERE: 
java.io.IOException: Invalid message length undefined
	at com.vaadin.server.communication.AtmospherePushConnection$FragmentedMessage.<init>(AtmospherePushConnection.java:77)
	at com.vaadin.server.communication.AtmospherePushConnection.receiveMessage(AtmospherePushConnection.java:208)
	at com.vaadin.server.communication.PushHandler$3.run(PushHandler.java:163)
	at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:253)
	at com.vaadin.server.communication.PushHandler.access$200(PushHandler.java:56)
	at com.vaadin.server.communication.PushHandler$1.onRequest(PushHandler.java:76)
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:187)
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:98)
	at org.atmosphere.container.TomcatWebSocketUtil.doService(TomcatWebSocketUtil.java:154)
	at org.atmosphere.container.Tomcat7Servlet30SupportWithWebSocket.service(Tomcat7Servlet30SupportWithWebSocket.java:62)
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:1809)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:434)
	at org.atmosphere.websocket.DefaultWebSocketProcessor$2.run(DefaultWebSocketProcessor.java:287)
	at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:281)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:305)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatchReader(DefaultWebSocketProcessor.java:645)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:406)
	at org.atmosphere.container.TomcatWebSocketHandler.onTextData(TomcatWebSocketHandler.java:100)
	at org.apache.catalina.websocket.StreamInbound.doOnTextData(StreamInbound.java:191)
	at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:139)
	at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:88)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: For input string: "undefined"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.vaadin.server.communication.AtmospherePushConnection$FragmentedMessage.<init>(AtmospherePushConnection.java:75)
	... 27 more

**Comment by davidsowerby** [comment]
This may be relevant, occurs at start up

WARNING: 
=================================================================
Vaadin is running in DEBUG MODE.
Add productionMode=true to web.xml to disable debug features.
To show debug window, add ?debug to your application URL.
=================================================================
Mar 02, 2015 7:00:24 PM com.vaadin.server.VaadinServletService checkAtmosphereSupport
WARNING: 
=================================================================
Vaadin depends on Atmosphere 2.2.4.vaadin2 but version 2.1.6 was found.
This might cause compatibility problems if push is used.
=================================================================
