### ISSUE TITLE
Notification error in handler

### ISSUE THREAD

**Issue by davidsowerby** [davidsowerby/krail#653]
Found in server log

>18:03:55.189  DEBUG DefaultVaadinNotification - Received information message 'uk.q3c.krail.core.user.notify.InformationNotificationMessage@1f55d4fc'
java.lang.RuntimeException: Error during publication of message
	at uk.q3c.krail.core.eventbus.DefaultEventBusErrorHandler.handleError(DefaultEventBusErrorHandler.java:33)
	at net.engio.mbassy.bus.AbstractPubSubSupport.handlePublicationError(AbstractPubSubSupport.java:106)
	at net.engio.mbassy.bus.SyncMessageBus.publish(SyncMessageBus.java:50)
	at uk.q3c.krail.core.user.notify.DefaultUserNotifier.notifyInformation(DefaultUserNotifier.java:56)
	at uk.q3c.krail.core.view.component.DefaultLocaleSelector.valueChange(DefaultLocaleSelector.java:133)
	at com.vaadin.ui.ComboBox.lambda$addValueChangeListener$bddd7469$1(ComboBox.java:682)
	at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:211)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:174)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1030)
	at com.vaadin.ui.AbstractSingleSelect.setSelectedFromClient(AbstractSingleSelect.java:236)
	at com.vaadin.ui.AbstractSingleSelect$1.select(AbstractSingleSelect.java:382)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:155)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:116)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:445)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:410)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:274)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1568)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:381)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at org.apache.onami.persist.PersistenceFilterImpl.doFilter(PersistenceFilterImpl.java:56)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Error during invocation of message handler. There might be an access rights problem. Do you use non public inner classes?
	at uk.q3c.krail.core.eventbus.DefaultEventBusErrorHandler.handleError(DefaultEventBusErrorHandler.java:33)
	at net.engio.mbassy.subscription.SubscriptionContext.handleError(SubscriptionContext.java:59)
	at net.engio.mbassy.dispatch.HandlerInvocation.handlePublicationError(HandlerInvocation.java:26)
	at net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invoke(ReflectiveHandlerInvocation.java:40)
	at net.engio.mbassy.dispatch.MessageDispatcher.dispatch(MessageDispatcher.java:30)
	at net.engio.mbassy.dispatch.FilteredMessageDispatcher.dispatch(FilteredMessageDispatcher.java:42)
	at net.engio.mbassy.subscription.Subscription.publish(Subscription.java:72)
	at net.engio.mbassy.bus.MessagePublication.execute(MessagePublication.java:49)
	at net.engio.mbassy.bus.SyncMessageBus.publish(SyncMessageBus.java:48)
	... 54 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invoke(ReflectiveHandlerInvocation.java:29)
	... 59 more
Caused by: java.lang.NoSuchMethodError: com.vaadin.ui.Notification.show(Ljava/lang/String;Lcom/vaadin/ui/Notification$Type;)Lcom/vaadin/ui/Notification;
	at uk.q3c.krail.core.user.notify.DefaultVaadinNotification.informationMessage(DefaultVaadinNotification.java:57)

**Comment by davidsowerby** [comment]
Believe, but not 100% sure, this was caused by a mix of Vaadin versions - the explicit setting of Vaadin version in build.gradle (vaadin plugin) had not been done in the test application 
Version correction was made in 22bdc21db16f3994077d53f7cf14ad31fad0491d
