### ISSUE TITLE
Push broken in Tomcat

### ISSUE THREAD

**Issue by davidsowerby** [davidsowerby/krail#673]
SEVERE: 
java.lang.IllegalStateException: Unable to configure jsr356 at that stage. No Servlet associated with Key[type=uk.q3c.krail.testapp.TestAppServlet, annotation=[none]]
	at org.atmosphere.util.IOUtils.guestRawServletPath(IOUtils.java:275)
	at org.atmosphere.util.IOUtils.guestServletPath(IOUtils.java:248)
	at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:63)
	at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:40)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.newCometSupport(DefaultAsyncSupportResolver.java:237)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolveWebSocket(DefaultAsyncSupportResolver.java:308)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolve(DefaultAsyncSupportResolver.java:294)
	at org.atmosphere.cpr.AtmosphereFramework.autoDetectContainer(AtmosphereFramework.java:2080)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:914)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:838)
	at com.vaadin.server.communication.PushRequestHandler.initAtmosphere(PushRequestHandler.java:212)
	at com.vaadin.server.communication.PushRequestHandler.<init>(PushRequestHandler.java:80)
	at com.vaadin.server.VaadinServletService.createRequestHandlers(VaadinServletService.java:68)
	at com.vaadin.server.VaadinService.init(VaadinService.java:216)
	at com.vaadin.server.VaadinServlet.createServletService(VaadinServlet.java:398)
	at com.vaadin.server.VaadinServlet.createServletService(VaadinServlet.java:377)
	at com.vaadin.server.VaadinServlet.init(VaadinServlet.java:207)
	at com.google.inject.servlet.ServletDefinition.init(ServletDefinition.java:120)
	at com.google.inject.servlet.ManagedServletPipeline.init(ManagedServletPipeline.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.initPipeline(ManagedFilterPipeline.java:103)
	at com.google.inject.servlet.GuiceFilter.init(GuiceFilter.java:226)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:285)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:266)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:108)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4590)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5233)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1860)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Mar 20, 2018 2:08:36 PM org.atmosphere.cpr.DefaultAsyncSupportResolver newCometSupport
WARNING: Failed to create AsyncSupport class: class org.atmosphere.container.JSR356AsyncSupport, error: java.lang.reflect.InvocationTargetException
Mar 20, 2018 2:08:36 PM org.atmosphere.cpr.DefaultAsyncSupportResolver newCometSupport
SEVERE: Real error: Unable to configure jsr356 at that stage
java.lang.IllegalStateException: Unable to configure jsr356 at that stage
	at org.atmosphere.util.IOUtils.guestRawServletPath(IOUtils.java:290)
	at org.atmosphere.util.IOUtils.guestServletPath(IOUtils.java:248)
	at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:63)
	at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:40)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.newCometSupport(DefaultAsyncSupportResolver.java:237)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolveWebSocket(DefaultAsyncSupportResolver.java:308)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolve(DefaultAsyncSupportResolver.java:294)
	at org.atmosphere.cpr.AtmosphereFramework.autoDetectContainer(AtmosphereFramework.java:2080)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:914)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:838)
	at com.vaadin.server.communication.PushRequestHandler.initAtmosphere(PushRequestHandler.java:212)
	at com.vaadin.server.communication.PushRequestHandler.<init>(PushRequestHandler.java:80)
	at com.vaadin.server.VaadinServletService.createRequestHandlers(VaadinServletService.java:68)
	at com.vaadin.server.VaadinService.init(VaadinService.java:216)
	at com.vaadin.server.VaadinServlet.createServletService(VaadinServlet.java:398)
	at com.vaadin.server.VaadinServlet.createServletService(VaadinServlet.java:377)
	at com.vaadin.server.VaadinServlet.init(VaadinServlet.java:207)
	at com.google.inject.servlet.ServletDefinition.init(ServletDefinition.java:120)
	at com.google.inject.servlet.ManagedServletPipeline.init(ManagedServletPipeline.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.initPipeline(ManagedFilterPipeline.java:103)
	at com.google.inject.servlet.GuiceFilter.init(GuiceFilter.java:226)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:285)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:266)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:108)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4590)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5233)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1860)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Mar 20, 2018 2:08:36 PM org.atmosphere.cpr.AtmosphereFramework init
SEVERE: Failed to initialize Atmosphere Framework
java.lang.NoClassDefFoundError: org/eclipse/jetty/continuation/ContinuationListener
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.newCometSupport(DefaultAsyncSupportResolver.java:236)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolveNativeCometSupport(DefaultAsyncSupportResolver.java:319)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolve(DefaultAsyncSupportResolver.java:299)
	at org.atmosphere.cpr.AtmosphereFramework.autoDetectContainer(AtmosphereFramework.java:2080)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:914)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:838)
	at com.vaadin.server.communication.PushRequestHandler.initAtmosphere(PushRequestHandler.java:212)
	at com.vaadin.server.communication.PushRequestHandler.<init>(PushRequestHandler.java:80)
	at com.vaadin.server.VaadinServletService.createRequestHandlers(VaadinServletService.java:68)
	at com.vaadin.server.VaadinService.init(VaadinService.java:216)
	at com.vaadin.server.VaadinServlet.createServletService(VaadinServlet.java:398)
	at com.vaadin.server.VaadinServlet.createServletService(VaadinServlet.java:377)
	at com.vaadin.server.VaadinServlet.init(VaadinServlet.java:207)
	at com.google.inject.servlet.ServletDefinition.init(ServletDefinition.java:120)
	at com.google.inject.servlet.ManagedServletPipeline.init(ManagedServletPipeline.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.initPipeline(ManagedFilterPipeline.java:103)
	at com.google.inject.servlet.GuiceFilter.init(GuiceFilter.java:226)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:285)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:266)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:108)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4590)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5233)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1860)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.continuation.ContinuationListener
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1285)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1119)
	... 37 more

Mar 20, 2018 2:08:36 PM com.vaadin.server.communication.PushRequestHandler <init>
WARNING: Failed to initialize Atmosphere for Key[type=uk.q3c.krail.testapp.TestAppServlet, annotation=[none]]. Push will not work.
java.lang.RuntimeException: Atmosphere init failed
	at com.vaadin.server.communication.PushRequestHandler.initAtmosphere(PushRequestHandler.java:220)
	at com.vaadin.server.communication.PushRequestHandler.<init>(PushRequestHandler.java:80)
	at com.vaadin.server.VaadinServletService.createRequestHandlers(VaadinServletService.java:68)
	at com.vaadin.server.VaadinService.init(VaadinService.java:216)
	at com.vaadin.server.VaadinServlet.createServletService(VaadinServlet.java:398)
	at com.vaadin.server.VaadinServlet.createServletService(VaadinServlet.java:377)
	at com.vaadin.server.VaadinServlet.init(VaadinServlet.java:207)
	at com.google.inject.servlet.ServletDefinition.init(ServletDefinition.java:120)
	at com.google.inject.servlet.ManagedServletPipeline.init(ManagedServletPipeline.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.initPipeline(ManagedFilterPipeline.java:103)
	at com.google.inject.servlet.GuiceFilter.init(GuiceFilter.java:226)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:285)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:266)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:108)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4590)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5233)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1860)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.servlet.ServletException: java.lang.NoClassDefFoundError: org/eclipse/jetty/continuation/ContinuationListener
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:955)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:838)
	at com.vaadin.server.communication.PushRequestHandler.initAtmosphere(PushRequestHandler.java:212)
	... 26 more
Caused by: java.lang.NoClassDefFoundError: org/eclipse/jetty/continuation/ContinuationListener
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.newCometSupport(DefaultAsyncSupportResolver.java:236)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolveNativeCometSupport(DefaultAsyncSupportResolver.java:319)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolve(DefaultAsyncSupportResolver.java:299)
	at org.atmosphere.cpr.AtmosphereFramework.autoDetectContainer(AtmosphereFramework.java:2080)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:914)
	... 28 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.continuation.ContinuationListener
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1285)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1119)
	... 37 more

**Comment by mcollovati** [comment]
I see two separated problems from stacktrace:

1) java.lang.IllegalStateException: Unable to configure jsr356 at that stage. No Servlet associated with Key[type=uk.q3c.krail.testapp.TestAppServlet, annotation=[none]]

When VaadinServlet is registered through Guice ServletModule atmosphere does not initialize properly because it cannot find the servlet through `ServletContext.getServletRegistration(...)` since Guice does not register servlets but runs them in `doFilter`

 As a workaround the servlet should be registered with the following init parameter
`org.atmosphere.container.JSR356AsyncSupport.mappingPath=/PUSH`

2) SEVERE: Failed to initialize Atmosphere Framework
java.lang.NoClassDefFoundError: org/eclipse/jetty/continuation/ContinuationListener

This seem a problem with dependencies in classpath. The root cause is `java.lang.ClassNotFoundException: org.eclipse.jetty.continuation.ContinuationListener` and it is probabily  thrown because the app is running on tomcat but in `WEB-INF/lib/` there are a bunch of *jetty* related jars.
Maybe finding this jars in classpath atmosphere is trying to load the wrong `AsynchronousProcessor`  (perhaps `JettyServlet30AsyncSupportWithWebSocket`)
